---
- name: Build System
  hosts: all
  gather_facts: true
  become: true
  tasks:
  - name: Register as user auto-subscribe to available content.
    redhat_subscription:
      state: present
      username: "{{ rhsm_username }}"
      password: "{{ rhsm_password }}"
      auto_attach: true
      
  - name: Disable all RHSM repositories
    rhsm_repository:
      name: '*'
      state: disabled

  - name: Enable a {{ item }} repos
    rhsm_repository:
      name: "{{ item }}"
    with_items: "{{ enabled_repos }}"

  - name: Add Bro Repo
    yum_repository:
      name: bro
      description: The Bro Network Security Monitor (CentOS_7)
      file: bro_repo
      baseurl: http://download.opensuse.org/repositories/network:/bro/CentOS_7/
      gpgcheck: yes
      gpgkey: http://download.opensuse.org/repositories/network:/bro/CentOS_7/repodata/repomd.xml.key
      enabled: yes
      
  - name: Install bro into instance
    yum:
      name: bro
      state: latest
