---
- name: Unit Test for Tool Image
  hosts: "{{ test_subject }}"
  gather_facts: true
  become: true
  tasks:

  - name: "Enable a repos for unit testing packages"
    rhsm_repository:
      name: "{{ item }}"
    with_items: "{{ enabled_repos }}"
    
  - name: Install packages to handle tests and upload artifacts from unit test
    yum:
      name: 
        - python2-swiftclient
        - openscap-scanner
        - scap-security-guide
      state: latest

  - name: Check Bro binary
    stat:
      path: /opt/bro/bin/bro
    register: bro_output
    
  - name: Output results of test to file                                                                     
    copy:                                                                                              
      content: "{{ bro_output }}" 
      dest: /tmp/bro_output.txt
      
  - name: Conduct Security Scan
    command: oscap xccdf eval --profile stig-rhel7-disa --report /tmp/ssg-rhel7-report.html --stig-viewer /tmp/results-stig.xml /usr/share/xml/scap/ssg/content/ssg-rhel7-ds.xml
    ignore_errors: yes
    
  - name: Create swift container for build
    command: swift --os-auth-url "{{ swift_auth_url }}" --auth-version 3 --os-project-name "{{ swift_project }}" --os-project-domain-name "{{ swift_domain }}" --os-username "{{ swift_username }}" --os-user-domain-name "{{ swift_domain }}" --os-password "{{ swift_password }}" post "{{ ansible_machine_id }}"

  - name: Upload Unit tests to object store
    command: swift --os-auth-url "{{ swift_auth_url }}" --auth-version 3 --os-project-name "{{ swift_project }}" --os-project-domain-name "{{ swift_domain }}" --os-username "{{ swift_username }}" --os-user-domain-name "{{ swift_domain }}" --os-password "{{ swift_password }}" upload "{{ ansible_machine_id }}" /tmp/bro_output.txt
  
  - name: Upload SCAP Report to object store
    command: swift --os-auth-url "{{ swift_auth_url }}" --auth-version 3 --os-project-name "{{ swift_project }}" --os-project-domain-name "{{ swift_domain }}" --os-username "{{ swift_username }}" --os-user-domain-name "{{ swift_domain }}" --os-password "{{ swift_password }}" upload "{{ ansible_machine_id }}" /tmp/ssg-rhel7-report.html 
  
  - name: Upload STIG Viewer Report to object store
    command: swift --os-auth-url "{{ swift_auth_url }}" --auth-version 3 --os-project-name "{{ swift_project }}" --os-project-domain-name "{{ swift_domain }}" --os-username "{{ swift_username }}" --os-user-domain-name "{{ swift_domain }}" --os-password "{{ swift_password }}" upload "{{ ansible_machine_id }}" /tmp/results-stig.xml
      
  - name: Harden System
    command: oscap xccdf eval --remediate --profile stig-rhel7-disa --report /tmp/ssg-rhel7-report-remediate.html --stig-viewer /tmp/results-stig-remediate.xml /usr/share/xml/scap/ssg/content/ssg-rhel7-ds.xml
    ignore_errors: yes
  
  - name: Upload Post Hardened SCAP Report  to object store
    command: swift --os-auth-url "{{ swift_auth_url }}" --auth-version 3 --os-project-name "{{ swift_project }}" --os-project-domain-name "{{ swift_domain }}" --os-username "{{ swift_username }}" --os-user-domain-name "{{ swift_domain }}" --os-password "{{ swift_password }}" upload "{{ ansible_machine_id }}" /tmp/ssg-rhel7-report-remediate.html
  
  - name: Upload Post Hardened STIG Viewer Report to object store
    command: swift --os-auth-url "{{ swift_auth_url }}" --auth-version 3 --os-project-name "{{ swift_project }}" --os-project-domain-name "{{ swift_domain }}" --os-username "{{ swift_username }}" --os-user-domain-name "{{ swift_domain }}" --os-password "{{ swift_password }}" upload "{{ ansible_machine_id }}" /tmp/results-stig-remediate.xml
