---
- name: Unit Test for Tool Image
  hosts: "{{ test_subject }}"
  gather_facts: true
  become: true
  tasks:
  - name:
    stat:
      path: /opt/bro/bin/bro
    register: bro_output
    
  - name: Output results of test to file                                                                     
    copy:                                                                                              
      content: "{{ bro_output }}" 
      dest: /tmp/bro_output.txt
