---
- name: Deploy on OpenStack
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Deploy an instance
    os_server:
      state: present
      name: webserver
      image: rhel
      key_name: precision
      wait: yes
      flavor: m1.small
      auto_floating_ip: yes
      network: private
